"""Initial models

Revision ID: 114f4e25d36e
Revises: 
Create Date: 2026-01-17 18:38:26.642577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114f4e25d36e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('embedding_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_entries_embedding_id'), 'knowledge_base_entries', ['embedding_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_entries_id'), 'knowledge_base_entries', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('file_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='fileuploadstatus'), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_uploads_id'), 'file_uploads', ['id'], unique=False)
    op.create_table('message_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=True),
    sa.Column('target_system', sa.String(), nullable=True),
    sa.Column('business_domain', sa.String(), nullable=True),
    sa.Column('column_structure', sa.JSON(), nullable=True),
    sa.Column('sample_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_descriptions_id'), 'message_descriptions', ['id'], unique=False)
    op.create_table('mapping_formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_description_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_column', sa.String(), nullable=False),
    sa.Column('target_column', sa.String(), nullable=False),
    sa.Column('transformation_type', sa.String(), nullable=False),
    sa.Column('transformation_rule', sa.Text(), nullable=False),
    sa.Column('example_input', sa.String(), nullable=True),
    sa.Column('example_output', sa.String(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_description_id'], ['message_descriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_formulas_id'), 'mapping_formulas', ['id'], unique=False)
    op.create_table('transformation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_upload_id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['file_upload_id'], ['file_uploads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformation_jobs_id'), 'transformation_jobs', ['id'], unique=False)
    op.create_table('validation_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transformation_job_id', sa.Integer(), nullable=False),
    sa.Column('accuracy_percentage', sa.Float(), nullable=False),
    sa.Column('row_count_match', sa.Boolean(), nullable=True),
    sa.Column('column_count_match', sa.Boolean(), nullable=True),
    sa.Column('total_cells', sa.Integer(), nullable=False),
    sa.Column('matching_cells', sa.Integer(), nullable=False),
    sa.Column('differing_cells', sa.Integer(), nullable=False),
    sa.Column('differences', sa.JSON(), nullable=True),
    sa.Column('overall_quality', sa.String(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['transformation_job_id'], ['transformation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_reports_id'), 'validation_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_reports_id'), table_name='validation_reports')
    op.drop_table('validation_reports')
    op.drop_index(op.f('ix_transformation_jobs_id'), table_name='transformation_jobs')
    op.drop_table('transformation_jobs')
    op.drop_index(op.f('ix_mapping_formulas_id'), table_name='mapping_formulas')
    op.drop_table('mapping_formulas')
    op.drop_index(op.f('ix_message_descriptions_id'), table_name='message_descriptions')
    op.drop_table('message_descriptions')
    op.drop_index(op.f('ix_file_uploads_id'), table_name='file_uploads')
    op.drop_table('file_uploads')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_knowledge_base_entries_id'), table_name='knowledge_base_entries')
    op.drop_index(op.f('ix_knowledge_base_entries_embedding_id'), table_name='knowledge_base_entries')
    op.drop_table('knowledge_base_entries')
    # ### end Alembic commands ###