"""Add structure_type to standard_elements

Revision ID: 204cb17928d1
Revises: 36fe59c9e292
Create Date: 2026-01-29 11:22:55.020029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204cb17928d1'
down_revision = '36fe59c9e292'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standard_elements', sa.Column('structure_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standard_elements', 'structure_type')
    # ### end Alembic commands ###