"""Add standard_elements table

Revision ID: 36fe59c9e292
Revises: fee55213cf3f
Create Date: 2026-01-29 09:33:12.250024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36fe59c9e292'
down_revision = 'fee55213cf3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###