"""Add hierarchical paths to mapping formulas

Revision ID: c6dbbe5125ef
Revises: 114f4e25d36e
Create Date: 2026-01-27 08:43:34.439869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6dbbe5125ef'
down_revision = '114f4e25d36e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping_formulas', sa.Column('source_path', sa.String(length=500), nullable=False))
    op.add_column('mapping_formulas', sa.Column('target_path', sa.String(length=500), nullable=False))
    op.add_column('mapping_formulas', sa.Column('source_level', sa.Integer(), nullable=True))
    op.add_column('mapping_formulas', sa.Column('target_level', sa.Integer(), nullable=True))
    op.alter_column('mapping_formulas', 'message_description_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mapping_formulas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mapping_formulas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('mapping_formulas_message_description_id_fkey', 'mapping_formulas', type_='foreignkey')
    op.create_foreign_key(None, 'mapping_formulas', 'message_descriptions', ['message_description_id'], ['id'], ondelete='CASCADE')
    op.drop_column('mapping_formulas', 'source_column')
    op.drop_column('mapping_formulas', 'target_column')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping_formulas', sa.Column('target_column', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('mapping_formulas', sa.Column('source_column', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mapping_formulas', type_='foreignkey')
    op.create_foreign_key('mapping_formulas_message_description_id_fkey', 'mapping_formulas', 'message_descriptions', ['message_description_id'], ['id'])
    op.alter_column('mapping_formulas', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('mapping_formulas', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('mapping_formulas', 'message_description_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('mapping_formulas', 'target_level')
    op.drop_column('mapping_formulas', 'source_level')
    op.drop_column('mapping_formulas', 'target_path')
    op.drop_column('mapping_formulas', 'source_path')
    # ### end Alembic commands ###