"""Add standard_elements table

Revision ID: fee55213cf3f
Revises: c6dbbe5125ef
Create Date: 2026-01-29 09:17:46.390179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee55213cf3f'
down_revision = 'c6dbbe5125ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###