import { useState, useEffect } from 'react';
import Layout from '../components/Layout';
import WorkflowSteps from '../components/WorkflowSteps';
import Card from '../components/Card';
import axios from 'axios';
import { toast } from 'react-toastify';
import { motion } from 'framer-motion';
import API_BASE_URL from '../config/api';

const API = `${API_BASE_URL}/api`;

const OutputsPage = () => {
  const [outputs, setOutputs] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => { loadData(); }, []);

  const loadData = async () => {
    try {
      const outputsResp = await axios.get(`${API}/transform/outputs`);
      setOutputs(outputsResp.data.files || []);
    } catch (error) {
      toast.error('Failed to load outputs');
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async (filename) => {
    try {
      const response = await axios.get(
        `${API}/transform/download/${filename}`,
        { responseType: 'blob' }
      );
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', filename);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
      toast.success('File downloaded!');
    } catch (error) {
      toast.error('Download failed');
    }
  };

  const getFileIcon = (filename) => {
    if (filename.endsWith('.xml')) return '🏦';
    if (filename.endsWith('.txt')) return '📄';
    if (filename.endsWith('.json')) return '📋';
    return '📄';
  };

  const getFileType = (filename) => {
    if (filename.includes('camt') || filename.includes('pacs')) return 'ISO 20022';
    if (filename.includes('MT') || filename.includes('mt')) return 'SWIFT MT';
    if (filename.endsWith('.xml')) return 'XML';
    return 'Output';
  };

  if (loading) {
    return (
      <Layout>
        <div style={{ textAlign: 'center', padding: '4rem', color: '#a0a0a0' }}>
          <div style={{ fontSize: '3rem', marginBottom: '1rem' }}>⏳</div>
          Loading...
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }}>

        <WorkflowSteps current="outputs" />

        {/* Header */}
        <div style={{ marginBottom: '2rem' }}>
          <h1 style={{
            fontSize: '2.5rem', fontWeight: '800', margin: 0,
            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent'
          }}>
            🚀 Outputs
          </h1>
          <p style={{ color: '#a0a0a0', marginTop: '0.5rem' }}>
            Files generated by Transform, on the Mapping page
          </p>
        </div>

        {/* Output Files */}
        <Card>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1.5rem' }}>
            <h2 style={{ color: 'white', fontSize: '1.3rem', margin: 0 }}>
              📂 Generated Files ({outputs.length})
            </h2>
            <button onClick={loadData} style={{ padding: '6px 14px',
              background: 'rgba(102,126,234,0.2)', color: '#667eea',
              border: '1px solid rgba(102,126,234,0.3)', borderRadius: '8px',
              fontSize: '0.82rem', cursor: 'pointer' }}>
              🔄 Refresh
            </button>
          </div>
          {outputs.length === 0 ? (
            <div style={{ textAlign: 'center', padding: '3rem', color: '#a0a0a0' }}>
              <div style={{ fontSize: '3rem', marginBottom: '1rem' }}>📭</div>
              <div>No outputs yet. Run a Transform from the Mapping page, or a Pipeline from Consommation.</div>
            </div>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              {outputs.map((output, idx) => (
                <motion.div key={idx} initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: idx * 0.05 }}
                  style={{ display: 'flex', alignItems: 'center', gap: '1rem', padding: '1rem',
                    background: 'rgba(255,255,255,0.03)', borderRadius: '10px',
                    border: '1px solid rgba(255,255,255,0.08)' }}>
                  <div style={{ fontSize: '1.5rem', width: '40px', height: '40px',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    background: 'rgba(102,126,234,0.15)', borderRadius: '8px' }}>
                    {getFileIcon(output.filename)}
                  </div>
                  <div style={{ flex: 1 }}>
                    <div style={{ color: 'white', fontWeight: '600', fontSize: '0.9rem' }}>
                      {output.filename}
                    </div>
                    <div style={{ display: 'flex', gap: '0.75rem', marginTop: '3px' }}>
                      <span style={{ color: '#6b7280', fontSize: '0.78rem' }}>
                        {(output.size / 1024).toFixed(2)} KB
                      </span>
                      <span style={{ color: '#6b7280', fontSize: '0.78rem' }}>
                        {new Date(output.created * 1000).toLocaleString()}
                      </span>
                      <span style={{ padding: '1px 8px', borderRadius: '4px', fontSize: '0.75rem',
                        background: 'rgba(102,126,234,0.15)', color: '#a78bfa' }}>
                        {getFileType(output.filename)}
                      </span>
                    </div>
                  </div>
                  <button onClick={() => handleDownload(output.filename)} style={{
                    padding: '6px 14px',
                    background: 'linear-gradient(135deg, #22c55e, #16a34a)',
                    color: 'white', border: 'none', borderRadius: '8px',
                    fontSize: '0.85rem', fontWeight: '600', cursor: 'pointer' }}>
                    ⬇️ Download
                  </button>
                </motion.div>
              ))}
            </div>
          )}
        </Card>
      </motion.div>
    </Layout>
  );
};

export default OutputsPage;
